spring.application.name=JO
server.port=9090
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/jo
spring.jpa.show-sql=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# https://www.devglan.com/online-tools/hmac-sha256-online
security.jwt.secret-key=17bb40e68a8d9f98a2a2bfeaff8f3e5ca28f4cbd066a66eeecc7cd02e8b34718
security.jwt.expiration-time=3600000